//
//  CoreDataStack.swift
//  MyMovies
//
//  Created by Dahna on 5/22/20.
//  Copyright Â© 2020 Lambda School. All rights reserved.
//

import Foundation
import CoreData

class CoreDataStack {
    
    static let shared = CoreDataStack()
    
    lazy var container: NSPersistentContainer = {
        let container = NSPersistentContainer(name: "MyMovies")
        container.loadPersistentStores { _, error in
            if let error = error {
                fatalError("Failed to load persistent stores: \(error)")
            }
        }
        return container
    }()
    
    var mainContext: NSManagedObjectContext {
        return container.viewContext
    }
    
    func save(context: NSManagedObjectContext = CoreDataStack.shared.mainContext) throws {
        var error: Error?
        
        // if we did perform (asynchronous call) in this case, it would automatically jump to line 43 and it would think that the error is always nil but that isn't true. That's why we need to performAndWait (synchronous call) to actually have to closure (do/catch block) finish and see if there is an error and handle it if necessary!!!!
        context.performAndWait {
            do {
                try context.save()
            } catch let saveError {
                error = saveError
            }
        }
        if let error = error { throw error }
    }
}
